[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "creyone_layer"
version = "1.0.0"
dependencies = [
  "torch>=2.0"
]
requires-python = ">=3.10"
authors = [
  {name = "Linqa Kiriyama", email = "kiriyamalq@gmail.com"},
]
description = "PyTorch layer building tools for CREYONE"
readme = "README.md"
license = {file = "LICENSE"}
keywords = []
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3 :: Only"
]

[project.urls]
Homepage = "https://example.com"
Documentation = "https://readthedocs.org"
Repository = "https://github.com/qnilix/creyone_layer.git"
"Bug Tracker" = "https://github.com/qnilix/creyone_layer/issues"
Changelog = "https://github.com/qnilix/creyone_layer/blob/master/CHANGELOG.md"

[tool.setuptools.packages.find]
where = ["."]
include = ["creyone_layer*"]